spring:
  profiles:
    active: dev #By default, the profile is "dev". In production, it will be replaced by "prod" to Azure's env variables
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,configprops,heapdump,httpexchanges,loggers,mappings,custom-beans
  endpoint:
    health:
        show-details: always
        probes:
          enabled: true
    env:
      show-values: always
    configprops:
      show-values: always
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true


info:
  app:
    name: @project.artifactId@
    description: A web application that manages artifacts and wizards for Hogwarts School of Witchcraft and Wizardry
    version: @project.version@
    author: Alvin Chang
    links:
      youtube: https://youtube.com/@BingyangWang
      github: https://github.com/tigerbalm62/hogwarts-artifacts-online

