spring:
  profiles:
    active: dev #By default, the profile is "dev". In production, it will be replaced by "prod" to Azure's env variables
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80
